### PR TITLE
Update to latest solidity 0.4.25

### PR DESCRIPTION
**Pull request by tbocek**
* Updated to latest version: 
  - solidity to 0.4.25
  - gradle to 4.10.2
  - com.jfrog.bintray to 1.8.4
* The windows binaries from the ethereum github site, release 0.4.25 has
  now 2 dlls more.
* The OSX binaries were compiled manually (without brew) and tested. Its now running, although
  the binary size is a larger.

### CODE REVIEW

**Comment by mkalinin** [comment]
Thanks for your awesome job 👍

**Comment by mkalinin** [comment]
Now uploaded on Bintray

**Comment by mkalinin** [comment]
@tbocek what branch/tag did you use to build macOS bindaries? It says: 
> This is a pre-release compiler version, please do not use it in production

**Comment by tbocek** [comment]
Hmm, when I run the binary, it does not show this message:

```
Thomass-iMac:build draft$ ./solc/solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25-develop.2018.9.26+commit.59dbf8f1.Darwin.appleclang
```

I used the instructions at https://github.com/ether-camp/solcJ/blob/master/instructions.md for manually compiling (not brew). For the checkout I used:

```git checkout tags/v0.4.25```

However for the alpine linux build (https://github.com/ether-camp/solcJ/blob/master/scripts/linux/Dockerfile), there is the following command, which I think could mute this message:

```
# don't use nightly versioning for releases
RUN echo -n > ../prerelease.txt
```

**Comment by zilm13** [comment]
@tbocek you need to compile something to see this, no notification in `version` output:
```
> ./solc --abi ethereumj-core/src/test/resources/solidity/file1.sol
Warning: This is a pre-release compiler version, please do not use it in production.
ethereumj-core/src/test/resources/solidity/file1.sol:6:5: Warning: No visibility specified. Defaulting to "public".
    function test() constant returns (uint) {
    ^ (Relevant source part starts here and spans across multiple lines).
ethereumj-core/src/test/resources/solidity/file1.sol:6:5: Warning: Function state mutability can be restricted to pure
    function test() constant returns (uint) {
    ^ (Relevant source part starts here and spans across multiple lines).

======= ethereumj-core/src/test/resources/solidity/file1.sol:test1 =======
Contract JSON ABI
[{"constant":true,"inputs":[],"name":"test","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
```

**Comment by mkalinin** [comment]
It looks odd to me that `git checkout tags/v0.4.25` results in `0.4.25-develop.2018.9.26+commit.59dbf8f1.Darwin.appleclang`

**Comment by mkalinin** [comment]
@tbocek Looks like you're right. Solidity [CI config](https://github.com/ethereum/solidity/blob/develop/.travis.yml#L165) says that if there is a build from `release` branch then empty `prerelease.txt` file is created which further defines build version without pre-release tag.

That is what should be done to build a _release_ version. Could you please try that and update macOS binaries? Then I'll replace bintray's artifact with updated one.

**Comment by tbocek** [comment]
I now added the release flag, but then I had the issue with the missing libz3 library, same as when compiling with brew. So I resolved this by shipping the libz3 library in solcJ (see #16).  Can you test it?

I also update the compiling instructions.

**Comment by mkalinin** [comment]
cool 👍  I'll check it locally before publishing on Bintray

**Comment by tbocek** [comment]
Awesome, thx. Libz3 is MIT licensed, so it should be ok to include it.

**Pull request merged**
