### PR TITLE
update solc to version 4.19

### PR DESCRIPTION
**Pull request by h2mch**

### CODE REVIEW

**Comment by cedricwalter** [comment]
Hi  

Do you have an ETA when it will be merged? i am depending on https://github.com/web3j/web3j-maven-plugin that still use Solc 0.4.10 and i would like to use the latest version.

Regards

**Comment by mkalinin** [comment]
@h2mch does it include only win binaries?

**Comment by h2mch** [comment]
no it contains linux und mac binary.

**Comment by mkalinin** [comment]
got it!

**Comment by k06a** [comment]
@cedricwalter do `web3j-maven-plugin` works fine for you? Looks like 0.2.0 version is not published to Maven Central yet, but 0.1.4 version depends on `solcJ` 0.4.19, which is not published too.

**Comment by cedricwalter** [comment]
@k06a not at all i am still using 1.2.0 (solc 0.4.10) but would like to use the latest solc compiler, 0.2.0 version is not available yet

**Pull request merged**
