### PR TITLE
Update to solc 0.4.24

### PR DESCRIPTION
**Pull request by tbocek**
Also removed manual compiling and using binaries from https://github.com/ethereum/solidity/releases.

### CODE REVIEW

**Comment by mkalinin** [comment]
What is the purpose of removing some files from scripts?
Could you, also, update README.md?

**Comment by mkalinin** [comment]
Fixes https://github.com/ether-camp/solcJ/issues/10

**Comment by tbocek** [comment]
The files in scripts were used to compile solc for windows and linux. Since the binaries are now downloaded from https://solidity.readthedocs.io/en/latest/installing-solidity.html#binary-packages within the gradle build process, they are not needed anymore. So I removed them.

The version numbers are updated in README.md in this pull request.

**Comment by mkalinin** [comment]
> The version numbers are updated in README.md in this pull request.

Ah, yes. Sorry.
I don't see any drawbacks in keeping old scripts. It is good to have an alternative way of getting those binaries. I am about to merge when you bring scripts back.

**Comment by tbocek** [comment]
Alright, now keeping the old scripts and explaining in the instructions why this directory is there.

**Comment by mkalinin** [comment]
Thanks for your awesome work!

**Comment by mkalinin** [comment]
https://dl.bintray.com/ethereum/maven/org/ethereum/solcJ-all/0.4.24/

**Comment by zilm13** [comment]
Both 0.4.23 and 0.4.24 not working for me on Mac, while 0.4.19 is ok
When compiling something, stdout and stderr both are empty, while exit code is 132

**Comment by tbocek** [comment]
I just noticed the same thing. A friend of mine that has a Mac and did not compile solc on his machine, reported that its missing the libz3 library. It seems that the binaries on Mac are not statically linked. I don't think that solidity will provide a Mac binary soon: https://github.com/ethereum/solidity/issues/3168. Thus, keeping up with new releases will be a pain for those who don't have a Mac.

**Pull request merged**
