### PR TITLE
update solc to version 4.23

### PR DESCRIPTION
**Pull request by MykolaMarkov**

### CODE REVIEW

**Comment by tbocek** [comment]
just wondering when it will be merged...

**Comment by mkalinin** [comment]
Can you guys add several things as were introduced by this PR: https://github.com/ether-camp/solcJ/pull/7/files

**Comment by mkalinin** [comment]
Cool 👍 will make a build today

**Comment by mkalinin** [comment]
@MykolaMarkov https://dl.bintray.com/ethereum/maven/org/ethereum/solcJ-all/0.4.23/
thanks a lot for keeping it up to date 👍

**Pull request merged**
