### PR TITLE
Upgrade to version 0.5.1, removed z3 dependency in the mac build

### PR DESCRIPTION
**Pull request by tbocek**
Please note, this update to 0.5.1 requires the pull request https://github.com/ethereum/ethereumj/pull/1243 as the command line interface changed a bit. I'm also building the mac binaries without z3.

### CODE REVIEW

**Comment by mkalinin** [comment]
good luck on that! 👍 Your efforts are much appreciated as always!

**Comment by tbocek** [comment]
Updated pull request for ethereumj with all my testcases now working: https://github.com/ethereum/ethereumj/pull/1244

**Comment by mkalinin** [comment]
This one is ready for merge, right?

**Comment by tbocek** [comment]
No, only with the release of ethereumj with commit ethereum/ethereumj#1244, otherwise you will have to compile your own jar to make it work. I would rather wait.

**Comment by mkalinin** [comment]
Shit, it would be much better if Solidity API kept here, in solcJ codebase.

**Comment by mkalinin** [comment]
@tbocek [EthereumJ `1.10.0`](https://github.com/ethereum/ethereumj/releases/tag/1.10.0) has been released. I am tend to merge this PR and release solcJ. But you might want to update `solc` to `0.5.2` version?

**Comment by tbocek** [comment]
@mkalinin Awesome, I updated to 0.5.2 and tested the Linux release with the testcase in https://github.com/ICOnator/Testonator. As usual Mac version was tested only to see if the command line interface is running and no dependencies are missing.

**Comment by mkalinin** [comment]
Publish on the Bintray. @tbocek many thanks!

**Pull request merged**
