### PR TITLE
Adding version 0.4.18 #4

### PR DESCRIPTION
**Pull request by flefevre**
Actions
-adding manually binary from ethereum web site

Review
-i didn't find the one for mac

Signed-off-by: Francois Le Fevre <francois.le-fevre@cea.fr>

### CODE REVIEW

**Comment by hooji** [comment]
Before merging all 3 platform binaries should be present, including for Mac.

These can be built as per project instructions.  I don't think this pull should be incorporated until updated to include all binaries.

**Comment by flefevre** [comment]
Dear Hooji,
I have tried multiple times and I was not able to generate the one from Mac. I am sorry for that. Just to inforce that the binaries provided by ethereum/solc are for linux and windows, not mac version is provided by default...
Hope you are able to generate them, since a lot of bugs have been provided in 0.4.18
I will appreciate your help.

**Comment by cedricwalter** [comment]
can be closed, since https://github.com/ether-camp/solcJ/pull/6 is merged and provide solc 0.4.19. No need to merge this PR to go back to solc 0.4.18

**Comment by flefevre** [comment]
Thanks for the feedback and the update

**Pull request closed without merging**
